"""Hand-judged target corpus, deliberately independent of resolver cleanup.

Expected literals describe the desired future behavior, not today's output.
Patterns document coverage; source payloads are synthetic German/EU retail data.
Only recognized mass/volume/count tokens are stripped; recognized count words are sizes; Tabs stay in names.
"""


def off(name_de=None, name=None, brands=None, quantity=None, pq=None,
        pq_unit=None, categories=None, image=None):
    product = {}
    for key, value in (("product_name_de", name_de), ("product_name", name),
                       ("brands", brands), ("quantity", quantity),
                       ("product_quantity", pq), ("product_quantity_unit", pq_unit),
                       ("categories", categories), ("image_url", image)):
        if value is not None:
            product[key] = value
    return {"status": 1, "product": product}


def case(id, group, barcode, sources, name, brand, quantity, category,
         image=None, patterns=()):
    return {"id": id, "category_group": group, "barcode": barcode,
            "sources": sources,
            "expected": {"name": name, "brand": brand, "quantity": quantity,
                         "category": category, "variant": None, "imageUrl": image},
            "patterns": patterns}


CORPUS = [
    case('fleisch_fisch_1', 'fleisch_fisch', '2900000000001',
         {'off': off(name_de='Gut Ponholz H\xe4hnchengeschnetzeltes 400g', brands='Gut Ponholz', quantity='400 g', categories='de:fleisch-fisch,en:other', image='https://images.example.org/corpus/1.jpg')},
         'H\xe4hnchengeschnetzeltes', 'Gut Ponholz', '400 g', 'fleisch fisch', 'https://images.example.org/corpus/1.jpg', ('P1', 'P16', 'P19', 'P3')),
    case('fleisch_fisch_2', 'fleisch_fisch', '2900000000002',
         {'off': off(name_de='Lachsfilet Gut Ponholz 750 g', brands='Gut Ponholz', quantity='750 g', categories='de:fleisch-fisch,en:other')},
         'Lachsfilet', 'Gut Ponholz', '750 g', 'fleisch fisch', None, ('P15', 'P16', 'P19', 'P2', 'P3')),
    case('fleisch_fisch_3', 'fleisch_fisch', '2900000000003',
         {'off': off(name_de='Rinderhackfleisch Gut Ponholz 500 g', brands='Gut Ponholz', quantity='500 g', categories='de:fleisch-fisch,en:other')},
         'Rinderhackfleisch', 'Gut Ponholz', '500 g', 'fleisch fisch', None, ('P15', 'P16', 'P19', 'P2', 'P3')),
    case('fleisch_fisch_4', 'fleisch_fisch', '2900000000004',
         {'off': off(name_de='Putenschnitzel 2 x 250 g', brands='Gut Ponholz', categories='de:fleisch-fisch,en:other', image='https://images.example.org/corpus/4.jpg')},
         'Putenschnitzel', 'Gut Ponholz', '2 x 250 g', 'fleisch fisch', 'https://images.example.org/corpus/4.jpg', ('P15', 'P16', 'P19', 'P4')),
    case('fleisch_fisch_5', 'fleisch_fisch', '2900000000005',
         {'off': off(name_de='Schweinefilet', brands='Gut Ponholz', quantity='1 kg', pq=1.0, pq_unit='kg', categories='de:fleisch-fisch,en:other')},
         'Schweinefilet', 'Gut Ponholz', '1 kg', 'fleisch fisch', None, ('P16', 'P19', 'P5')),
    case('fleisch_fisch_6', 'fleisch_fisch', '2900000000006',
         {'off': off(name_de='H\xc4HNCHENBRUST', brands='Gut Ponholz', quantity='1 kg', categories='de:fleisch-fisch,en:other')},
         'H\xe4hnchenbrust', 'Gut Ponholz', '1 kg', 'fleisch fisch', None, ('P16', 'P19', 'P5', 'P6')),
    case('fleisch_fisch_7', 'fleisch_fisch', '2900000000007',
         {'off': off(name_de='forellenfilet', brands='Gut Ponholz', quantity='500 g', categories='de:fleisch-fisch,en:other', image='https://images.example.org/corpus/7.jpg')},
         'Forellenfilet', 'Gut Ponholz', '500 g', 'fleisch fisch', 'https://images.example.org/corpus/7.jpg', ('P16', 'P19', 'P5', 'P6')),
    case('fleisch_fisch_8', 'fleisch_fisch', '2900000000008',
         {'off': off(name_de='H\xc3\xa4hnchenkeulen', brands='Gut Ponholz', quantity='250 g', categories='de:fleisch-fisch,en:other')},
         'H\xe4hnchenkeulen', 'Gut Ponholz', '250 g', 'fleisch fisch', None, ('P16', 'P19', 'P7')),
    case('fleisch_fisch_9', 'fleisch_fisch', '2900000000009',
         {'off': off(name_de='Gut Ponholz Seelachsfilet Naturhof 2x250g', brands='Gut Ponholz,Naturhof', quantity='2 x 250 g', categories='de:fleisch-fisch,en:other')},
         'Seelachsfilet', 'Gut Ponholz', '2 x 250 g', 'fleisch fisch', None, ('P1', 'P15', 'P16', 'P19', 'P3', 'P8')),
    case('fleisch_fisch_10', 'fleisch_fisch', '2900000000010',
         {'off': off(name_de='Rindergulasch', quantity='10 Stk', categories='de:fleisch-fisch,en:other', image='https://images.example.org/corpus/10.jpg')},
         'Rindergulasch', None, '10 Stk', 'fleisch fisch', 'https://images.example.org/corpus/10.jpg', ('P10', 'P15', 'P16', 'P19', 'P5')),
    case('fleisch_fisch_11', 'fleisch_fisch', '2900000000011',
         {'off': off(name='Chicken Breast', brands='Gut Ponholz', quantity='500 g', categories='de:fleisch-fisch,en:other')},
         'Chicken Breast', 'Gut Ponholz', '500 g', 'fleisch fisch', None, ('P11', 'P16', 'P19')),
    case('fleisch_fisch_12', 'fleisch_fisch', '2900000000012',
         {'off': off(name_de='Kalbsschnitzel', brands='Gut Ponholz', quantity='400 g', categories='de:fleisch-fisch'), 'obf': off(name_de='Kalbsschnitzel', brands='Gut Ponholz', quantity='400 g', categories='de:fleisch-fisch'), 'opf': off(name_de='Kalbsschnitzel 400 g', brands='Gut Ponholz', categories='de:fleisch-fisch')},
         'Kalbsschnitzel', 'Gut Ponholz', '400 g', 'fleisch fisch', None, ('P11', 'P12', 'P16', 'P19')),
    case('wurst_aufschnitt_1', 'wurst_aufschnitt', '2900000000013',
         {'off': off(name_de='Metzgerhof Kochschinken 400g', brands='Metzgerhof', quantity='400 g', categories='de:wurst-aufschnitt,en:other', image='https://images.example.org/corpus/13.jpg')},
         'Kochschinken', 'Metzgerhof', '400 g', 'wurst aufschnitt', 'https://images.example.org/corpus/13.jpg', ('P1', 'P16', 'P19', 'P3')),
    case('wurst_aufschnitt_2', 'wurst_aufschnitt', '2900000000014',
         {'off': off(name_de='Salami Metzgerhof 750 g', brands='Metzgerhof', quantity='750 g', categories='de:wurst-aufschnitt,en:other')},
         'Salami', 'Metzgerhof', '750 g', 'wurst aufschnitt', None, ('P16', 'P19', 'P2', 'P3')),
    case('wurst_aufschnitt_3', 'wurst_aufschnitt', '2900000000015',
         {'off': off(name_de='Leberwurst Metzgerhof 500 g', brands='Metzgerhof', quantity='500 g', categories='de:wurst-aufschnitt,en:other')},
         'Leberwurst', 'Metzgerhof', '500 g', 'wurst aufschnitt', None, ('P16', 'P19', 'P2', 'P3')),
    case('wurst_aufschnitt_4', 'wurst_aufschnitt', '2900000000016',
         {'off': off(name_de='Putenaufschnitt 2 x 250 g', brands='Metzgerhof', categories='de:wurst-aufschnitt,en:other', image='https://images.example.org/corpus/16.jpg')},
         'Putenaufschnitt', 'Metzgerhof', '2 x 250 g', 'wurst aufschnitt', 'https://images.example.org/corpus/16.jpg', ('P15', 'P16', 'P19', 'P4')),
    case('wurst_aufschnitt_5', 'wurst_aufschnitt', '2900000000017',
         {'off': off(name_de='Bierschinken', brands='Metzgerhof', quantity='1 kg', pq=1.0, pq_unit='kg', categories='de:wurst-aufschnitt,en:other')},
         'Bierschinken', 'Metzgerhof', '1 kg', 'wurst aufschnitt', None, ('P16', 'P19', 'P5')),
    case('wurst_aufschnitt_6', 'wurst_aufschnitt', '2900000000018',
         {'off': off(name_de='FLEISCHWURST', brands='Metzgerhof', quantity='1 kg', categories='de:wurst-aufschnitt,en:other')},
         'Fleischwurst', 'Metzgerhof', '1 kg', 'wurst aufschnitt', None, ('P16', 'P19', 'P5', 'P6')),
    case('wurst_aufschnitt_7', 'wurst_aufschnitt', '2900000000019',
         {'off': off(name_de='mortadella', brands='Metzgerhof', quantity='500 g', categories='de:wurst-aufschnitt,en:other', image='https://images.example.org/corpus/19.jpg')},
         'Mortadella', 'Metzgerhof', '500 g', 'wurst aufschnitt', 'https://images.example.org/corpus/19.jpg', ('P16', 'P19', 'P5', 'P6')),
    case('wurst_aufschnitt_8', 'wurst_aufschnitt', '2900000000020',
         {'off': off(name_de='Gefl\xc3\xbcgelwurst', brands='Metzgerhof', quantity='250 g', categories='de:wurst-aufschnitt,en:other')},
         'Gefl\xfcgelwurst', 'Metzgerhof', '250 g', 'wurst aufschnitt', None, ('P16', 'P19', 'P7')),
    case('wurst_aufschnitt_9', 'wurst_aufschnitt', '2900000000021',
         {'off': off(name_de='Metzgerhof Schinkenw\xfcrfel Naturhof 2x250g', brands='Metzgerhof,Naturhof', quantity='2 x 250 g', categories='de:wurst-aufschnitt,en:other')},
         'Schinkenw\xfcrfel', 'Metzgerhof', '2 x 250 g', 'wurst aufschnitt', None, ('P1', 'P15', 'P16', 'P19', 'P3', 'P8')),
    case('wurst_aufschnitt_10', 'wurst_aufschnitt', '2900000000022',
         {'off': off(name_de='Bratwurst', quantity='10 Stk', categories='de:wurst-aufschnitt,en:other', image='https://images.example.org/corpus/22.jpg')},
         'Bratwurst', None, '10 Stk', 'wurst aufschnitt', 'https://images.example.org/corpus/22.jpg', ('P10', 'P16', 'P19', 'P5')),
    case('wurst_aufschnitt_11', 'wurst_aufschnitt', '2900000000023',
         {'off': off(name='Smoked Ham', brands='Metzgerhof', quantity='500 g', categories='de:wurst-aufschnitt,en:other')},
         'Smoked Ham', 'Metzgerhof', '500 g', 'wurst aufschnitt', None, ('P11', 'P16', 'P19')),
    case('wurst_aufschnitt_12', 'wurst_aufschnitt', '2900000000024',
         {'off': off(name_de='Lyoner', brands='Metzgerhof', quantity='400 g', categories='de:wurst-aufschnitt'), 'obf': off(name_de='Lyoner', brands='Metzgerhof', quantity='400 g', categories='de:wurst-aufschnitt'), 'opf': off(name_de='Lyoner 400 g', brands='Metzgerhof', categories='de:wurst-aufschnitt')},
         'Lyoner', 'Metzgerhof', '400 g', 'wurst aufschnitt', None, ('P11', 'P12', 'P16', 'P19')),
    case('milch_kaese_eier_1', 'milch_kaese_eier', '2900000000025',
         {'off': off(name_de='Alpenhof Gouda 400g', brands='Alpenhof', quantity='400 g', categories='de:milchprodukte,en:other', image='https://images.example.org/corpus/25.jpg')},
         'Gouda', 'Alpenhof', '400 g', 'milchprodukte', 'https://images.example.org/corpus/25.jpg', ('P1', 'P16', 'P19', 'P3')),
    case('milch_kaese_eier_2', 'milch_kaese_eier', '2900000000026',
         {'off': off(name_de='Quark Alpenhof 750 g', brands='Alpenhof', quantity='750 g', categories='de:milchprodukte,en:other')},
         'Quark', 'Alpenhof', '750 g', 'milchprodukte', None, ('P16', 'P19', 'P2', 'P3')),
    case('milch_kaese_eier_3', 'milch_kaese_eier', '2900000000027',
         {'off': off(name_de='Butter Alpenhof 500 g', brands='Alpenhof', quantity='500 g', categories='de:milchprodukte,en:other')},
         'Butter', 'Alpenhof', '500 g', 'milchprodukte', None, ('P16', 'P19', 'P2', 'P3')),
    case('milch_kaese_eier_4', 'milch_kaese_eier', '2900000000028',
         {'off': off(name_de='Joghurt Erdbeere 2 x 250 g', brands='Alpenhof', categories='de:milchprodukte,en:other', image='https://images.example.org/corpus/28.jpg')},
         'Joghurt Erdbeere', 'Alpenhof', '2 x 250 g', 'milchprodukte', 'https://images.example.org/corpus/28.jpg', ('P15', 'P16', 'P19', 'P4')),
    case('milch_kaese_eier_5', 'milch_kaese_eier', '2900000000029',
         {'off': off(name_de='Frischk\xe4se', brands='Alpenhof', quantity='1 kg', pq=1.0, pq_unit='kg', categories='de:milchprodukte,en:other')},
         'Frischk\xe4se', 'Alpenhof', '1 kg', 'milchprodukte', None, ('P16', 'P19', 'P5')),
    case('milch_kaese_eier_6', 'milch_kaese_eier', '2900000000030',
         {'off': off(name_de='VOLLMILCH', brands='Alpenhof', quantity='1 l', categories='de:milchprodukte,en:other')},
         'Vollmilch', 'Alpenhof', '1 l', 'milchprodukte', None, ('P16', 'P19', 'P5', 'P6')),
    case('milch_kaese_eier_7', 'milch_kaese_eier', '2900000000031',
         {'off': off(name_de='buttermilch', brands='Alpenhof', quantity='500 ml', categories='de:milchprodukte,en:other', image='https://images.example.org/corpus/31.jpg')},
         'Buttermilch', 'Alpenhof', '500 ml', 'milchprodukte', 'https://images.example.org/corpus/31.jpg', ('P16', 'P19', 'P5', 'P6')),
    case('milch_kaese_eier_8', 'milch_kaese_eier', '2900000000032',
         {'off': off(name_de='K\xc3\xa4sew\xc3\xbcrfel', brands='Alpenhof', quantity='250 g', categories='de:milchprodukte,en:other')},
         'K\xe4sew\xfcrfel', 'Alpenhof', '250 g', 'milchprodukte', None, ('P16', 'P19', 'P7')),
    case('milch_kaese_eier_9', 'milch_kaese_eier', '2900000000033',
         {'off': off(name_de='Alpenhof Camembert Naturhof 2x250g', brands='Alpenhof,Naturhof', quantity='2 x 250 g', categories='de:milchprodukte,en:other')},
         'Camembert', 'Alpenhof', '2 x 250 g', 'milchprodukte', None, ('P1', 'P15', 'P16', 'P19', 'P3', 'P8')),
    case('milch_kaese_eier_10', 'milch_kaese_eier', '2900000000034',
         {'off': off(name_de='Eier', quantity='10 Stk', categories='de:milchprodukte,en:other', image='https://images.example.org/corpus/34.jpg')},
         'Eier', None, '10 Stk', 'milchprodukte', 'https://images.example.org/corpus/34.jpg', ('P10', 'P16', 'P19', 'P5')),
    case('milch_kaese_eier_11', 'milch_kaese_eier', '2900000000035',
         {'off': off(name='Greek Yogurt', brands='Alpenhof', quantity='500 g', categories='de:milchprodukte,en:other')},
         'Greek Yogurt', 'Alpenhof', '500 g', 'milchprodukte', None, ('P11', 'P16', 'P19')),
    case('milch_kaese_eier_12', 'milch_kaese_eier', '2900000000036',
         {'off': off(name_de='Mozzarella', brands='Alpenhof', quantity='400 g', categories='de:milchprodukte'), 'obf': off(name_de='Mozzarella', brands='Alpenhof', quantity='400 g', categories='de:milchprodukte'), 'opf': off(name_de='Mozzarella 400 g', brands='Alpenhof', categories='de:milchprodukte')},
         'Mozzarella', 'Alpenhof', '400 g', 'milchprodukte', None, ('P11', 'P12', 'P16', 'P19')),
    case('obst_gemuese_1', 'obst_gemuese', '2900000000037',
         {'off': off(name_de='Gartenland \xc4pfel 400g', brands='Gartenland', quantity='400 g', categories='de:obst-gemuese,en:other', image='https://images.example.org/corpus/37.jpg')},
         '\xc4pfel', 'Gartenland', '400 g', 'obst gemuese', 'https://images.example.org/corpus/37.jpg', ('P1', 'P16', 'P19', 'P3')),
    case('obst_gemuese_2', 'obst_gemuese', '2900000000038',
         {'off': off(name_de='Karotten Gartenland 750 g', brands='Gartenland', quantity='750 g', categories='de:obst-gemuese,en:other')},
         'Karotten', 'Gartenland', '750 g', 'obst gemuese', None, ('P16', 'P19', 'P2', 'P3')),
    case('obst_gemuese_3', 'obst_gemuese', '2900000000039',
         {'off': off(name_de='Tomaten Gartenland 500 g', brands='Gartenland', quantity='500 g', categories='de:obst-gemuese,en:other')},
         'Tomaten', 'Gartenland', '500 g', 'obst gemuese', None, ('P16', 'P19', 'P2', 'P3')),
    case('obst_gemuese_4', 'obst_gemuese', '2900000000040',
         {'off': off(name_de='Kartoffeln 2 x 250 g', brands='Gartenland', categories='de:obst-gemuese,en:other', image='https://images.example.org/corpus/40.jpg')},
         'Kartoffeln', 'Gartenland', '2 x 250 g', 'obst gemuese', 'https://images.example.org/corpus/40.jpg', ('P15', 'P16', 'P19', 'P4')),
    case('obst_gemuese_5', 'obst_gemuese', '2900000000041',
         {'off': off(name_de='Gurken', brands='Gartenland', quantity='1 kg', pq=1.0, pq_unit='kg', categories='de:obst-gemuese,en:other')},
         'Gurken', 'Gartenland', '1 kg', 'obst gemuese', None, ('P16', 'P19', 'P5')),
    case('obst_gemuese_6', 'obst_gemuese', '2900000000042',
         {'off': off(name_de='BIRNEN', brands='Gartenland', quantity='1 kg', categories='de:obst-gemuese,en:other')},
         'Birnen', 'Gartenland', '1 kg', 'obst gemuese', None, ('P16', 'P19', 'P5', 'P6')),
    case('obst_gemuese_7', 'obst_gemuese', '2900000000043',
         {'off': off(name_de='paprika', brands='Gartenland', quantity='500 g', categories='de:obst-gemuese,en:other', image='https://images.example.org/corpus/43.jpg')},
         'Paprika', 'Gartenland', '500 g', 'obst gemuese', 'https://images.example.org/corpus/43.jpg', ('P15', 'P16', 'P19', 'P5', 'P6')),
    case('obst_gemuese_8', 'obst_gemuese', '2900000000044',
         {'off': off(name_de='S\xc3\xbc\xc3\x9fkartoffeln', brands='Gartenland', quantity='250 g', categories='de:obst-gemuese,en:other')},
         'S\xfc\xdfkartoffeln', 'Gartenland', '250 g', 'obst gemuese', None, ('P16', 'P19', 'P7')),
    case('obst_gemuese_9', 'obst_gemuese', '2900000000045',
         {'off': off(name_de='Gartenland Zucchini Naturhof 2x250g', brands='Gartenland,Naturhof', quantity='2 x 250 g', categories='de:obst-gemuese,en:other')},
         'Zucchini', 'Gartenland', '2 x 250 g', 'obst gemuese', None, ('P1', 'P15', 'P16', 'P19', 'P3', 'P8')),
    case('obst_gemuese_10', 'obst_gemuese', '2900000000046',
         {'off': off(name_de='Champignons', quantity='10 Stk', categories='de:obst-gemuese,en:other', image='https://images.example.org/corpus/46.jpg')},
         'Champignons', None, '10 Stk', 'obst gemuese', 'https://images.example.org/corpus/46.jpg', ('P10', 'P16', 'P19', 'P5')),
    case('obst_gemuese_11', 'obst_gemuese', '2900000000047',
         {'off': off(name='Green Beans', brands='Gartenland', quantity='500 g', categories='de:obst-gemuese,en:other')},
         'Green Beans', 'Gartenland', '500 g', 'obst gemuese', None, ('P11', 'P16', 'P19')),
    case('obst_gemuese_12', 'obst_gemuese', '2900000000048',
         {'off': off(name_de='Brokkoli', brands='Gartenland', quantity='400 g', categories='de:obst-gemuese'), 'obf': off(name_de='Brokkoli', brands='Gartenland', quantity='400 g', categories='de:obst-gemuese'), 'opf': off(name_de='Brokkoli 400 g', brands='Gartenland', categories='de:obst-gemuese')},
         'Brokkoli', 'Gartenland', '400 g', 'obst gemuese', None, ('P11', 'P12', 'P16', 'P19')),
    case('backwaren_nudeln_reis_1', 'backwaren_nudeln_reis', '2900000000049',
         {'off': off(name_de='Kornland Spaghetti 400g', brands='Kornland', quantity='400 g', categories='de:getreideprodukte,en:other', image='https://images.example.org/corpus/49.jpg')},
         'Spaghetti', 'Kornland', '400 g', 'getreideprodukte', 'https://images.example.org/corpus/49.jpg', ('P1', 'P16', 'P19', 'P3')),
    case('backwaren_nudeln_reis_2', 'backwaren_nudeln_reis', '2900000000050',
         {'off': off(name_de='Vollkornbrot Kornland 750 g', brands='Kornland', quantity='750 g', categories='de:getreideprodukte,en:other')},
         'Vollkornbrot', 'Kornland', '750 g', 'getreideprodukte', None, ('P16', 'P19', 'P2', 'P3')),
    case('backwaren_nudeln_reis_3', 'backwaren_nudeln_reis', '2900000000051',
         {'off': off(name_de='Basmatireis Kornland 500 g', brands='Kornland', quantity='500 g', categories='de:getreideprodukte,en:other')},
         'Basmatireis', 'Kornland', '500 g', 'getreideprodukte', None, ('P16', 'P19', 'P2', 'P3')),
    case('backwaren_nudeln_reis_4', 'backwaren_nudeln_reis', '2900000000052',
         {'off': off(name_de='Penne 2 x 250 g', brands='Kornland', categories='de:getreideprodukte,en:other', image='https://images.example.org/corpus/52.jpg')},
         'Penne', 'Kornland', '2 x 250 g', 'getreideprodukte', 'https://images.example.org/corpus/52.jpg', ('P15', 'P16', 'P19', 'P4')),
    case('backwaren_nudeln_reis_5', 'backwaren_nudeln_reis', '2900000000053',
         {'off': off(name_de='Haferflocken', brands='Kornland', quantity='1 kg', pq=1.0, pq_unit='kg', categories='de:getreideprodukte,en:other')},
         'Haferflocken', 'Kornland', '1 kg', 'getreideprodukte', None, ('P16', 'P19', 'P5')),
    case('backwaren_nudeln_reis_6', 'backwaren_nudeln_reis', '2900000000054',
         {'off': off(name_de='KN\xc4CKEBROT', brands='Kornland', quantity='1 kg', categories='de:getreideprodukte,en:other')},
         'Kn\xe4ckebrot', 'Kornland', '1 kg', 'getreideprodukte', None, ('P16', 'P19', 'P5', 'P6')),
    case('backwaren_nudeln_reis_7', 'backwaren_nudeln_reis', '2900000000055',
         {'off': off(name_de='toastbrot', brands='Kornland', quantity='500 g', categories='de:getreideprodukte,en:other', image='https://images.example.org/corpus/55.jpg')},
         'Toastbrot', 'Kornland', '500 g', 'getreideprodukte', 'https://images.example.org/corpus/55.jpg', ('P16', 'P19', 'P5', 'P6')),
    case('backwaren_nudeln_reis_8', 'backwaren_nudeln_reis', '2900000000056',
         {'off': off(name_de='Br\xc3\xb6tchen', brands='Kornland', quantity='250 g', categories='de:getreideprodukte,en:other')},
         'Br\xf6tchen', 'Kornland', '250 g', 'getreideprodukte', None, ('P16', 'P19', 'P7')),
    case('backwaren_nudeln_reis_9', 'backwaren_nudeln_reis', '2900000000057',
         {'off': off(name_de='Kornland Dinkelmehl Naturhof 2x250g', brands='Kornland,Naturhof', quantity='2 x 250 g', categories='de:getreideprodukte,en:other')},
         'Dinkelmehl', 'Kornland', '2 x 250 g', 'getreideprodukte', None, ('P1', 'P15', 'P16', 'P19', 'P3', 'P8')),
    case('backwaren_nudeln_reis_10', 'backwaren_nudeln_reis', '2900000000058',
         {'off': off(name_de='Bulgur', quantity='10 Stk', categories='de:getreideprodukte,en:other', image='https://images.example.org/corpus/58.jpg')},
         'Bulgur', None, '10 Stk', 'getreideprodukte', 'https://images.example.org/corpus/58.jpg', ('P10', 'P16', 'P19', 'P5')),
    case('backwaren_nudeln_reis_11', 'backwaren_nudeln_reis', '2900000000059',
         {'off': off(name='Brown Rice', brands='Kornland', quantity='500 g', categories='de:getreideprodukte,en:other')},
         'Brown Rice', 'Kornland', '500 g', 'getreideprodukte', None, ('P11', 'P16', 'P19')),
    case('backwaren_nudeln_reis_12', 'backwaren_nudeln_reis', '2900000000060',
         {'off': off(name_de='Lasagneplatten', brands='Kornland', quantity='400 g', categories='de:getreideprodukte'), 'obf': off(name_de='Lasagneplatten', brands='Kornland', quantity='400 g', categories='de:getreideprodukte'), 'opf': off(name_de='Lasagneplatten 400 g', brands='Kornland', categories='de:getreideprodukte')},
         'Lasagneplatten', 'Kornland', '400 g', 'getreideprodukte', None, ('P11', 'P12', 'P16', 'P19')),
    case('konserven_saucen_oele_1', 'konserven_saucen_oele', '2900000000061',
         {'off': off(name_de='Landk\xfcche Tomatensauce 400g', brands='Landk\xfcche', quantity='400 g', categories='de:konserven-saucen,en:other', image='https://images.example.org/corpus/61.jpg')},
         'Tomatensauce', 'Landk\xfcche', '400 g', 'konserven saucen', 'https://images.example.org/corpus/61.jpg', ('P1', 'P16', 'P19', 'P3')),
    case('konserven_saucen_oele_2', 'konserven_saucen_oele', '2900000000062',
         {'off': off(name_de='Oliven\xf6l Landk\xfcche 750 ml', brands='Landk\xfcche', quantity='750 ml', categories='de:konserven-saucen,en:other')},
         'Oliven\xf6l', 'Landk\xfcche', '750 ml', 'konserven saucen', None, ('P16', 'P19', 'P2', 'P3')),
    case('konserven_saucen_oele_3', 'konserven_saucen_oele', '2900000000063',
         {'off': off(name_de='Kidneybohnen Landk\xfcche 500 g', brands='Landk\xfcche', quantity='500 g', categories='de:konserven-saucen,en:other')},
         'Kidneybohnen', 'Landk\xfcche', '500 g', 'konserven saucen', None, ('P16', 'P19', 'P2', 'P3')),
    case('konserven_saucen_oele_4', 'konserven_saucen_oele', '2900000000064',
         {'off': off(name_de='Kichererbsen 2 x 250 g', brands='Landk\xfcche', categories='de:konserven-saucen,en:other', image='https://images.example.org/corpus/64.jpg')},
         'Kichererbsen', 'Landk\xfcche', '2 x 250 g', 'konserven saucen', 'https://images.example.org/corpus/64.jpg', ('P15', 'P16', 'P19', 'P4')),
    case('konserven_saucen_oele_5', 'konserven_saucen_oele', '2900000000065',
         {'off': off(name_de='Senf', brands='Landk\xfcche', quantity='1 kg', pq=1.0, pq_unit='kg', categories='de:konserven-saucen,en:other')},
         'Senf', 'Landk\xfcche', '1 kg', 'konserven saucen', None, ('P16', 'P19', 'P5')),
    case('konserven_saucen_oele_6', 'konserven_saucen_oele', '2900000000066',
         {'off': off(name_de='SONNENBLUMEN\xd6L', brands='Landk\xfcche', quantity='1 l', categories='de:konserven-saucen,en:other')},
         'Sonnenblumen\xf6l', 'Landk\xfcche', '1 l', 'konserven saucen', None, ('P16', 'P19', 'P5', 'P6')),
    case('konserven_saucen_oele_7', 'konserven_saucen_oele', '2900000000067',
         {'off': off(name_de='erbsen', brands='Landk\xfcche', quantity='500 g', categories='de:konserven-saucen,en:other', image='https://images.example.org/corpus/67.jpg')},
         'Erbsen', 'Landk\xfcche', '500 g', 'konserven saucen', 'https://images.example.org/corpus/67.jpg', ('P16', 'P19', 'P5', 'P6')),
    case('konserven_saucen_oele_8', 'konserven_saucen_oele', '2900000000068',
         {'off': off(name_de='Gem\xc3\xbcsebr\xc3\xbche', brands='Landk\xfcche', quantity='250 g', categories='de:konserven-saucen,en:other')},
         'Gem\xfcsebr\xfche', 'Landk\xfcche', '250 g', 'konserven saucen', None, ('P16', 'P19', 'P7')),
    case('konserven_saucen_oele_9', 'konserven_saucen_oele', '2900000000069',
         {'off': off(name_de='Landk\xfcche Passierte Tomaten Naturhof 2x250g', brands='Landk\xfcche,Naturhof', quantity='2 x 250 g', categories='de:konserven-saucen,en:other')},
         'Passierte Tomaten', 'Landk\xfcche', '2 x 250 g', 'konserven saucen', None, ('P1', 'P15', 'P16', 'P19', 'P3', 'P8')),
    case('konserven_saucen_oele_10', 'konserven_saucen_oele', '2900000000070',
         {'off': off(name_de='Apfelmus', quantity='10 Stk', categories='de:konserven-saucen,en:other', image='https://images.example.org/corpus/70.jpg')},
         'Apfelmus', None, '10 Stk', 'konserven saucen', 'https://images.example.org/corpus/70.jpg', ('P10', 'P16', 'P19', 'P5')),
    case('konserven_saucen_oele_11', 'konserven_saucen_oele', '2900000000071',
         {'off': off(name='Chopped Tomatoes', brands='Landk\xfcche', quantity='500 g', categories='de:konserven-saucen,en:other')},
         'Chopped Tomatoes', 'Landk\xfcche', '500 g', 'konserven saucen', None, ('P11', 'P16', 'P19')),
    case('konserven_saucen_oele_12', 'konserven_saucen_oele', '2900000000072',
         {'off': off(name_de='Kokosmilch', brands='Landk\xfcche', quantity='400 ml', categories='de:konserven-saucen'), 'obf': off(name_de='Kokosmilch', brands='Landk\xfcche', quantity='400 ml', categories='de:konserven-saucen'), 'opf': off(name_de='Kokosmilch 400 ml', brands='Landk\xfcche', categories='de:konserven-saucen')},
         'Kokosmilch', 'Landk\xfcche', '400 ml', 'konserven saucen', None, ('P11', 'P12', 'P16', 'P19')),
    case('snacks_suesswaren_1', 'snacks_suesswaren', '2900000000073',
         {'off': off(name_de='Naschwerk Schokolade 400g', brands='Naschwerk', quantity='400 g', categories='de:snacks-suesswaren,en:other', image='https://images.example.org/corpus/73.jpg')},
         'Schokolade', 'Naschwerk', '400 g', 'snacks suesswaren', 'https://images.example.org/corpus/73.jpg', ('P1', 'P16', 'P19', 'P3')),
    case('snacks_suesswaren_2', 'snacks_suesswaren', '2900000000074',
         {'off': off(name_de='Chips Paprika Naschwerk 750 g', brands='Naschwerk', quantity='750 g', categories='de:snacks-suesswaren,en:other')},
         'Chips Paprika', 'Naschwerk', '750 g', 'snacks suesswaren', None, ('P15', 'P16', 'P19', 'P2', 'P3')),
    case('snacks_suesswaren_3', 'snacks_suesswaren', '2900000000075',
         {'off': off(name_de='Gummib\xe4rchen Naschwerk 500 g', brands='Naschwerk', quantity='500 g', categories='de:snacks-suesswaren,en:other')},
         'Gummib\xe4rchen', 'Naschwerk', '500 g', 'snacks suesswaren', None, ('P16', 'P19', 'P2', 'P3')),
    case('snacks_suesswaren_4', 'snacks_suesswaren', '2900000000076',
         {'off': off(name_de='Butterkekse 2 x 250 g', brands='Naschwerk', categories='de:snacks-suesswaren,en:other', image='https://images.example.org/corpus/76.jpg')},
         'Butterkekse', 'Naschwerk', '2 x 250 g', 'snacks suesswaren', 'https://images.example.org/corpus/76.jpg', ('P15', 'P16', 'P19', 'P4')),
    case('snacks_suesswaren_5', 'snacks_suesswaren', '2900000000077',
         {'off': off(name_de='Studentenfutter', brands='Naschwerk', quantity='1 kg', pq=1.0, pq_unit='kg', categories='de:snacks-suesswaren,en:other')},
         'Studentenfutter', 'Naschwerk', '1 kg', 'snacks suesswaren', None, ('P16', 'P19', 'P5')),
    case('snacks_suesswaren_6', 'snacks_suesswaren', '2900000000078',
         {'off': off(name_de='SALZSTANGEN', brands='Naschwerk', quantity='1 kg', categories='de:snacks-suesswaren,en:other')},
         'Salzstangen', 'Naschwerk', '1 kg', 'snacks suesswaren', None, ('P16', 'P19', 'P5', 'P6')),
    case('snacks_suesswaren_7', 'snacks_suesswaren', '2900000000079',
         {'off': off(name_de='fruchtgummi', brands='Naschwerk', quantity='500 g', categories='de:snacks-suesswaren,en:other', image='https://images.example.org/corpus/79.jpg')},
         'Fruchtgummi', 'Naschwerk', '500 g', 'snacks suesswaren', 'https://images.example.org/corpus/79.jpg', ('P16', 'P19', 'P5', 'P6')),
    case('snacks_suesswaren_8', 'snacks_suesswaren', '2900000000080',
         {'off': off(name_de='M\xc3\xbcsliriegel', brands='Naschwerk', quantity='250 g', categories='de:snacks-suesswaren,en:other')},
         'M\xfcsliriegel', 'Naschwerk', '250 g', 'snacks suesswaren', None, ('P16', 'P19', 'P7')),
    case('snacks_suesswaren_9', 'snacks_suesswaren', '2900000000081',
         {'off': off(name_de='Naschwerk Nusscreme Naturhof 2x250g', brands='Naschwerk,Naturhof', quantity='2 x 250 g', categories='de:snacks-suesswaren,en:other')},
         'Nusscreme', 'Naschwerk', '2 x 250 g', 'snacks suesswaren', None, ('P1', 'P15', 'P16', 'P19', 'P3', 'P8')),
    case('snacks_suesswaren_10', 'snacks_suesswaren', '2900000000082',
         {'off': off(name_de='Popcorn', quantity='10 Stk', categories='de:snacks-suesswaren,en:other', image='https://images.example.org/corpus/82.jpg')},
         'Popcorn', None, '10 Stk', 'snacks suesswaren', 'https://images.example.org/corpus/82.jpg', ('P10', 'P16', 'P19', 'P5')),
    case('snacks_suesswaren_11', 'snacks_suesswaren', '2900000000083',
         {'off': off(name='Dark Chocolate', brands='Naschwerk', quantity='500 g', categories='de:snacks-suesswaren,en:other')},
         'Dark Chocolate', 'Naschwerk', '500 g', 'snacks suesswaren', None, ('P11', 'P16', 'P19')),
    case('snacks_suesswaren_12', 'snacks_suesswaren', '2900000000084',
         {'off': off(name_de='Waffeln', brands='Naschwerk', quantity='400 g', categories='de:snacks-suesswaren'), 'obf': off(name_de='Waffeln', brands='Naschwerk', quantity='400 g', categories='de:snacks-suesswaren'), 'opf': off(name_de='Waffeln 400 g', brands='Naschwerk', categories='de:snacks-suesswaren')},
         'Waffeln', 'Naschwerk', '400 g', 'snacks suesswaren', None, ('P11', 'P12', 'P16', 'P19')),
    case('getraenke_alkoholfrei_1', 'getraenke_alkoholfrei', '2900000000085',
         {'off': off(name_de='Quellklar Mineralwasser 1,5L', brands='Quellklar', quantity='1,5 l', categories='de:alkoholfreie-getraenke,en:other', image='https://images.example.org/corpus/85.jpg')},
         'Mineralwasser', 'Quellklar', '1,5 l', 'alkoholfreie getraenke', 'https://images.example.org/corpus/85.jpg', ('P1', 'P16', 'P19', 'P3')),
    case('getraenke_alkoholfrei_2', 'getraenke_alkoholfrei', '2900000000086',
         {'off': off(name_de='Cola Zero Quellklar 750ml', brands='Quellklar', quantity='750 ml', categories='de:alkoholfreie-getraenke,en:other')},
         'Cola Zero', 'Quellklar', '750 ml', 'alkoholfreie getraenke', None, ('P15', 'P16', 'P19', 'P2', 'P3')),
    case('getraenke_alkoholfrei_3', 'getraenke_alkoholfrei', '2900000000087',
         {'off': off(name_de='Apfelsaft Quellklar 33 cl', brands='Quellklar', quantity='33 cl', categories='de:alkoholfreie-getraenke,en:other')},
         'Apfelsaft', 'Quellklar', '33 cl', 'alkoholfreie getraenke', None, ('P16', 'P19', 'P2', 'P3')),
    case('getraenke_alkoholfrei_4', 'getraenke_alkoholfrei', '2900000000088',
         {'off': off(name_de='Orangenlimonade 6 x 0,33 l', brands='Quellklar', categories='de:alkoholfreie-getraenke,en:other', image='https://images.example.org/corpus/88.jpg')},
         'Orangenlimonade', 'Quellklar', '6 x 0,33 l', 'alkoholfreie getraenke', 'https://images.example.org/corpus/88.jpg', ('P15', 'P16', 'P19', 'P4')),
    case('getraenke_alkoholfrei_5', 'getraenke_alkoholfrei', '2900000000089',
         {'off': off(name_de='Eistee Pfirsich', brands='Quellklar', quantity='1 l', pq=1.0, pq_unit='l', categories='de:alkoholfreie-getraenke,en:other')},
         'Eistee Pfirsich', 'Quellklar', '1 l', 'alkoholfreie getraenke', None, ('P15', 'P16', 'P19', 'P5')),
    case('getraenke_alkoholfrei_6', 'getraenke_alkoholfrei', '2900000000090',
         {'off': off(name_de='TRAUBENSAFT', brands='Quellklar', quantity='1,5 l', categories='de:alkoholfreie-getraenke,en:other')},
         'Traubensaft', 'Quellklar', '1,5 l', 'alkoholfreie getraenke', None, ('P16', 'P19', 'P5', 'P6')),
    case('getraenke_alkoholfrei_7', 'getraenke_alkoholfrei', '2900000000091',
         {'off': off(name_de='haferdrink', brands='Quellklar', quantity='500 ml', categories='de:alkoholfreie-getraenke,en:other', image='https://images.example.org/corpus/91.jpg')},
         'Haferdrink', 'Quellklar', '500 ml', 'alkoholfreie getraenke', 'https://images.example.org/corpus/91.jpg', ('P16', 'P19', 'P5', 'P6')),
    case('getraenke_alkoholfrei_8', 'getraenke_alkoholfrei', '2900000000092',
         {'off': off(name_de='Fr\xc3\xbcchtetee', brands='Quellklar', quantity='250 ml', categories='de:alkoholfreie-getraenke,en:other')},
         'Fr\xfcchtetee', 'Quellklar', '250 ml', 'alkoholfreie getraenke', None, ('P16', 'P19', 'P7')),
    case('getraenke_alkoholfrei_9', 'getraenke_alkoholfrei', '2900000000093',
         {'off': off(name_de='Quellklar Zitronenlimonade Naturhof 2x250ml', brands='Quellklar,Naturhof', quantity='2 x 250 ml', categories='de:alkoholfreie-getraenke,en:other')},
         'Zitronenlimonade', 'Quellklar', '2 x 250 ml', 'alkoholfreie getraenke', None, ('P1', 'P15', 'P16', 'P19', 'P3', 'P8')),
    case('getraenke_alkoholfrei_10', 'getraenke_alkoholfrei', '2900000000094',
         {'off': off(name_de='Tonic Water', quantity='0,33 l', categories='de:alkoholfreie-getraenke,en:other', image='https://images.example.org/corpus/94.jpg')},
         'Tonic Water', None, '0,33 l', 'alkoholfreie getraenke', 'https://images.example.org/corpus/94.jpg', ('P10', 'P16', 'P19', 'P5')),
    case('getraenke_alkoholfrei_11', 'getraenke_alkoholfrei', '2900000000095',
         {'off': off(name='Orange Juice', brands='Quellklar', quantity='33 cl', categories='de:alkoholfreie-getraenke,en:other')},
         'Orange Juice', 'Quellklar', '33 cl', 'alkoholfreie getraenke', None, ('P11', 'P16', 'P19')),
    case('getraenke_alkoholfrei_12', 'getraenke_alkoholfrei', '2900000000096',
         {'off': off(name_de='Multivitaminsaft', brands='Quellklar', quantity='1 l', categories='de:alkoholfreie-getraenke'), 'obf': off(name_de='Multivitaminsaft', brands='Quellklar', quantity='1 l', categories='de:alkoholfreie-getraenke'), 'opf': off(name_de='Multivitaminsaft 1 l', brands='Quellklar', categories='de:alkoholfreie-getraenke')},
         'Multivitaminsaft', 'Quellklar', '1 l', 'alkoholfreie getraenke', None, ('P11', 'P12', 'P16', 'P19')),
    case('getraenke_alkohol_1', 'getraenke_alkohol', '2900000000097',
         {'off': off(name_de='Kellerkrone Pils 1,5L', brands='Kellerkrone', quantity='1,5 l', categories='de:alkoholische-getraenke,en:other', image='https://images.example.org/corpus/97.jpg')},
         'Pils', 'Kellerkrone', '1,5 l', 'alkoholische getraenke', 'https://images.example.org/corpus/97.jpg', ('P1', 'P16', 'P19', 'P3')),
    case('getraenke_alkohol_2', 'getraenke_alkohol', '2900000000098',
         {'off': off(name_de='Rotwein Kellerkrone 750ml', brands='Kellerkrone', quantity='750 ml', categories='de:alkoholische-getraenke,en:other')},
         'Rotwein', 'Kellerkrone', '750 ml', 'alkoholische getraenke', None, ('P16', 'P19', 'P2', 'P3')),
    case('getraenke_alkohol_3', 'getraenke_alkohol', '2900000000099',
         {'off': off(name_de='Wei\xdfwein Kellerkrone 33 cl', brands='Kellerkrone', quantity='33 cl', categories='de:alkoholische-getraenke,en:other')},
         'Wei\xdfwein', 'Kellerkrone', '33 cl', 'alkoholische getraenke', None, ('P16', 'P19', 'P2', 'P3')),
    case('getraenke_alkohol_4', 'getraenke_alkohol', '2900000000100',
         {'off': off(name_de='Weizenbier 6 x 0,33 l', brands='Kellerkrone', categories='de:alkoholische-getraenke,en:other', image='https://images.example.org/corpus/100.jpg')},
         'Weizenbier', 'Kellerkrone', '6 x 0,33 l', 'alkoholische getraenke', 'https://images.example.org/corpus/100.jpg', ('P15', 'P16', 'P19', 'P4')),
    case('getraenke_alkohol_5', 'getraenke_alkohol', '2900000000101',
         {'off': off(name_de='Ros\xe9wein', brands='Kellerkrone', quantity='1 l', pq=1.0, pq_unit='l', categories='de:alkoholische-getraenke,en:other')},
         'Ros\xe9wein', 'Kellerkrone', '1 l', 'alkoholische getraenke', None, ('P16', 'P19', 'P5')),
    case('getraenke_alkohol_6', 'getraenke_alkohol', '2900000000102',
         {'off': off(name_de='SEKT', brands='Kellerkrone', quantity='1,5 l', categories='de:alkoholische-getraenke,en:other')},
         'Sekt', 'Kellerkrone', '1,5 l', 'alkoholische getraenke', None, ('P16', 'P19', 'P5', 'P6')),
    case('getraenke_alkohol_7', 'getraenke_alkohol', '2900000000103',
         {'off': off(name_de='radler', brands='Kellerkrone', quantity='500 ml', categories='de:alkoholische-getraenke,en:other', image='https://images.example.org/corpus/103.jpg')},
         'Radler', 'Kellerkrone', '500 ml', 'alkoholische getraenke', 'https://images.example.org/corpus/103.jpg', ('P16', 'P19', 'P5', 'P6')),
    case('getraenke_alkohol_8', 'getraenke_alkohol', '2900000000104',
         {'off': off(name_de='Kr\xc3\xa4uterlik\xc3\xa4r', brands='Kellerkrone', quantity='250 ml', categories='de:alkoholische-getraenke,en:other')},
         'Kr\xe4uterlik\xe4r', 'Kellerkrone', '250 ml', 'alkoholische getraenke', None, ('P16', 'P19', 'P7')),
    case('getraenke_alkohol_9', 'getraenke_alkohol', '2900000000105',
         {'off': off(name_de='Kellerkrone Gin Naturhof 2x250ml', brands='Kellerkrone,Naturhof', quantity='2 x 250 ml', categories='de:alkoholische-getraenke,en:other')},
         'Gin', 'Kellerkrone', '2 x 250 ml', 'alkoholische getraenke', None, ('P1', 'P15', 'P16', 'P19', 'P3', 'P8')),
    case('getraenke_alkohol_10', 'getraenke_alkohol', '2900000000106',
         {'off': off(name_de='Portwein', quantity='0,33 l', categories='de:alkoholische-getraenke,en:other', image='https://images.example.org/corpus/106.jpg')},
         'Portwein', None, '0,33 l', 'alkoholische getraenke', 'https://images.example.org/corpus/106.jpg', ('P10', 'P16', 'P19', 'P5')),
    case('getraenke_alkohol_11', 'getraenke_alkohol', '2900000000107',
         {'off': off(name='Dry Cider', brands='Kellerkrone', quantity='33 cl', categories='de:alkoholische-getraenke,en:other')},
         'Dry Cider', 'Kellerkrone', '33 cl', 'alkoholische getraenke', None, ('P11', 'P16', 'P19')),
    case('getraenke_alkohol_12', 'getraenke_alkohol', '2900000000108',
         {'off': off(name_de='Lagerbier', brands='Kellerkrone', quantity='1 l', categories='de:alkoholische-getraenke'), 'obf': off(name_de='Lagerbier', brands='Kellerkrone', quantity='1 l', categories='de:alkoholische-getraenke'), 'opf': off(name_de='Lagerbier 1 l', brands='Kellerkrone', categories='de:alkoholische-getraenke')},
         'Lagerbier', 'Kellerkrone', '1 l', 'alkoholische getraenke', None, ('P11', 'P12', 'P16', 'P19')),
    case('tiefkuehl_1', 'tiefkuehl', '2900000000109',
         {'off': off(name_de='Frostgarten Pizza Margherita 400g', brands='Frostgarten', quantity='400 g', categories='de:tiefkuehlkost,en:other', image='https://images.example.org/corpus/109.jpg')},
         'Pizza Margherita', 'Frostgarten', '400 g', 'tiefkuehlkost', 'https://images.example.org/corpus/109.jpg', ('P1', 'P15', 'P16', 'P19', 'P3')),
    case('tiefkuehl_2', 'tiefkuehl', '2900000000110',
         {'off': off(name_de='Blattspinat Frostgarten 750 g', brands='Frostgarten', quantity='750 g', categories='de:tiefkuehlkost,en:other')},
         'Blattspinat', 'Frostgarten', '750 g', 'tiefkuehlkost', None, ('P16', 'P19', 'P2', 'P3')),
    case('tiefkuehl_3', 'tiefkuehl', '2900000000111',
         {'off': off(name_de='Pommes Frites Frostgarten 500 g', brands='Frostgarten', quantity='500 g', categories='de:tiefkuehlkost,en:other')},
         'Pommes Frites', 'Frostgarten', '500 g', 'tiefkuehlkost', None, ('P16', 'P19', 'P2', 'P3')),
    case('tiefkuehl_4', 'tiefkuehl', '2900000000112',
         {'off': off(name_de='Gem\xfcsemischung 2 x 250 g', brands='Frostgarten', categories='de:tiefkuehlkost,en:other', image='https://images.example.org/corpus/112.jpg')},
         'Gem\xfcsemischung', 'Frostgarten', '2 x 250 g', 'tiefkuehlkost', 'https://images.example.org/corpus/112.jpg', ('P15', 'P16', 'P19', 'P4')),
    case('tiefkuehl_5', 'tiefkuehl', '2900000000113',
         {'off': off(name_de='Vanilleeis', brands='Frostgarten', quantity='1 kg', pq=1.0, pq_unit='kg', categories='de:tiefkuehlkost,en:other')},
         'Vanilleeis', 'Frostgarten', '1 kg', 'tiefkuehlkost', None, ('P15', 'P16', 'P19', 'P5')),
    case('tiefkuehl_6', 'tiefkuehl', '2900000000114',
         {'off': off(name_de='HIMBEEREN', brands='Frostgarten', quantity='1 kg', categories='de:tiefkuehlkost,en:other')},
         'Himbeeren', 'Frostgarten', '1 kg', 'tiefkuehlkost', None, ('P16', 'P19', 'P5', 'P6')),
    case('tiefkuehl_7', 'tiefkuehl', '2900000000115',
         {'off': off(name_de='brokkolir\xf6schen', brands='Frostgarten', quantity='500 g', categories='de:tiefkuehlkost,en:other', image='https://images.example.org/corpus/115.jpg')},
         'Brokkolir\xf6schen', 'Frostgarten', '500 g', 'tiefkuehlkost', 'https://images.example.org/corpus/115.jpg', ('P16', 'P19', 'P5', 'P6')),
    case('tiefkuehl_8', 'tiefkuehl', '2900000000116',
         {'off': off(name_de='Kr\xc3\xa4utermischung', brands='Frostgarten', quantity='250 g', categories='de:tiefkuehlkost,en:other')},
         'Kr\xe4utermischung', 'Frostgarten', '250 g', 'tiefkuehlkost', None, ('P16', 'P19', 'P7')),
    case('tiefkuehl_9', 'tiefkuehl', '2900000000117',
         {'off': off(name_de='Frostgarten Fischst\xe4bchen Naturhof 2x250g', brands='Frostgarten,Naturhof', quantity='2 x 250 g', categories='de:tiefkuehlkost,en:other')},
         'Fischst\xe4bchen', 'Frostgarten', '2 x 250 g', 'tiefkuehlkost', None, ('P1', 'P15', 'P16', 'P19', 'P3', 'P8')),
    case('tiefkuehl_10', 'tiefkuehl', '2900000000118',
         {'off': off(name_de='Erbsen', quantity='10 Stk', categories='de:tiefkuehlkost,en:other', image='https://images.example.org/corpus/118.jpg')},
         'Erbsen', None, '10 Stk', 'tiefkuehlkost', 'https://images.example.org/corpus/118.jpg', ('P10', 'P16', 'P19', 'P5')),
    case('tiefkuehl_11', 'tiefkuehl', '2900000000119',
         {'off': off(name='Vegetable Lasagne', brands='Frostgarten', quantity='500 g', categories='de:tiefkuehlkost,en:other')},
         'Vegetable Lasagne', 'Frostgarten', '500 g', 'tiefkuehlkost', None, ('P11', 'P16', 'P19')),
    case('tiefkuehl_12', 'tiefkuehl', '2900000000120',
         {'off': off(name_de='Rahmspinat', brands='Frostgarten', quantity='400 g', categories='de:tiefkuehlkost'), 'obf': off(name_de='Rahmspinat', brands='Frostgarten', quantity='400 g', categories='de:tiefkuehlkost'), 'opf': off(name_de='Rahmspinat 400 g', brands='Frostgarten', categories='de:tiefkuehlkost')},
         'Rahmspinat', 'Frostgarten', '400 g', 'tiefkuehlkost', None, ('P11', 'P12', 'P16', 'P19')),
    case('haushalt_reinigung_1', 'haushalt_reinigung', '2900000000121',
         {'opf': off(name_de='Sauberfix Toilettenpapier 8 Rollen', brands='Sauberfix', categories='de:haushaltswaren,en:other', image='https://images.example.org/corpus/121.jpg')},
         'Toilettenpapier', 'Sauberfix', '8 Rollen', 'haushaltswaren', 'https://images.example.org/corpus/121.jpg', ('P1', 'P16', 'P19', 'P20', 'P3')),
    case('haushalt_reinigung_2', 'haushalt_reinigung', '2900000000122',
         {'opf': off(name_de='Sp\xfclmaschinentabs 40 Tabs Sauberfix', brands='Sauberfix', categories='de:haushaltswaren,en:other')},
         'Sp\xfclmaschinentabs 40 Tabs', 'Sauberfix', None, 'haushaltswaren', None, ('P16', 'P19', 'P2', 'P20', 'P3')),
    case('haushalt_reinigung_3', 'haushalt_reinigung', '2900000000123',
         {'opf': off(name_de='AA Batterien Sauberfix 8 Stk', brands='Sauberfix', quantity='8 Stk', categories='de:haushaltswaren,en:other')},
         'AA Batterien', 'Sauberfix', '8 Stk', 'haushaltswaren', None, ('P16', 'P19', 'P2', 'P20', 'P3')),
    case('haushalt_reinigung_4', 'haushalt_reinigung', '2900000000124',
         {'opf': off(name_de='M\xfcllbeutel 10 Stk', brands='Sauberfix', categories='de:haushaltswaren,en:other', image='https://images.example.org/corpus/124.jpg')},
         'M\xfcllbeutel', 'Sauberfix', '10 Stk', 'haushaltswaren', 'https://images.example.org/corpus/124.jpg', ('P15', 'P16', 'P19', 'P20', 'P4')),
    case('haushalt_reinigung_5', 'haushalt_reinigung', '2900000000125',
         {'opf': off(name_de='Allzweckreiniger', brands='Sauberfix', quantity='1 l', pq=1.0, pq_unit='l', categories='de:haushaltswaren,en:other')},
         'Allzweckreiniger', 'Sauberfix', '1 l', 'haushaltswaren', None, ('P16', 'P19', 'P20', 'P5')),
    case('haushalt_reinigung_6', 'haushalt_reinigung', '2900000000126',
         {'opf': off(name_de='SP\xdcLMITTEL', brands='Sauberfix', quantity='500 ml', categories='de:haushaltswaren,en:other')},
         'Sp\xfclmittel', 'Sauberfix', '500 ml', 'haushaltswaren', None, ('P16', 'P19', 'P20', 'P5', 'P6')),
    case('haushalt_reinigung_7', 'haushalt_reinigung', '2900000000127',
         {'opf': off(name_de='waschpulver', brands='Sauberfix', quantity='1 kg', categories='de:haushaltswaren,en:other', image='https://images.example.org/corpus/127.jpg')},
         'Waschpulver', 'Sauberfix', '1 kg', 'haushaltswaren', 'https://images.example.org/corpus/127.jpg', ('P16', 'P19', 'P20', 'P5', 'P6')),
    case('haushalt_reinigung_8', 'haushalt_reinigung', '2900000000128',
         {'opf': off(name_de='K\xc3\xbcchent\xc3\xbccher 4 Rollen', brands='Sauberfix', quantity='4 Rollen', categories='de:haushaltswaren,en:other')},
         'K\xfcchent\xfccher', 'Sauberfix', '4 Rollen', 'haushaltswaren', None, ('P16', 'P19', 'P20', 'P7')),
    case('haushalt_reinigung_9', 'haushalt_reinigung', '2900000000129',
         {'opf': off(name_de='Sauberfix Glasreiniger Naturhof 2 x 250 ml', brands='Sauberfix,Naturhof', quantity='2 x 250 ml', categories='de:haushaltswaren,en:other')},
         'Glasreiniger', 'Sauberfix', '2 x 250 ml', 'haushaltswaren', None, ('P1', 'P15', 'P16', 'P19', 'P20', 'P3', 'P8')),
    case('haushalt_reinigung_10', 'haushalt_reinigung', '2900000000130',
         {'opf': off(name_de='Schw\xe4mme', quantity='10 Stk', categories='de:haushaltswaren,en:other', image='https://images.example.org/corpus/130.jpg')},
         'Schw\xe4mme', None, '10 Stk', 'haushaltswaren', 'https://images.example.org/corpus/130.jpg', ('P10', 'P16', 'P19', 'P20', 'P5')),
    case('haushalt_reinigung_11', 'haushalt_reinigung', '2900000000131',
         {'opf': off(name='Laundry Detergent', brands='Sauberfix', quantity='1 l', categories='de:haushaltswaren,en:other')},
         'Laundry Detergent', 'Sauberfix', '1 l', 'haushaltswaren', None, ('P11', 'P16', 'P19', 'P20')),
    case('haushalt_reinigung_12', 'haushalt_reinigung', '2900000000132',
         {'off': off(name_de='WC Reiniger', brands='Sauberfix', quantity='750 ml', categories='de:haushaltswaren'), 'obf': off(name_de='WC Reiniger', brands='Sauberfix', quantity='750 ml', categories='de:haushaltswaren'), 'opf': off(name_de='WC Reiniger 750 ml', brands='Sauberfix', categories='de:haushaltswaren')},
         'WC Reiniger', 'Sauberfix', '750 ml', 'haushaltswaren', None, ('P11', 'P12', 'P16', 'P19', 'P20')),
    case('drogerie_kosmetik_1', 'drogerie_kosmetik', '2900000000133',
         {'obf': off(name_de='Sanftzeit Duschgel 250 ml', brands='Sanftzeit', quantity='250 ml', categories='de:koerperpflege,en:other', image='https://images.example.org/corpus/133.jpg')},
         'Duschgel', 'Sanftzeit', '250 ml', 'koerperpflege', 'https://images.example.org/corpus/133.jpg', ('P1', 'P16', 'P19', 'P3')),
    case('drogerie_kosmetik_2', 'drogerie_kosmetik', '2900000000134',
         {'obf': off(name_de='Shampoo Sanftzeit 750ml', brands='Sanftzeit', quantity='750 ml', categories='de:koerperpflege,en:other')},
         'Shampoo', 'Sanftzeit', '750 ml', 'koerperpflege', None, ('P16', 'P19', 'P2', 'P3')),
    case('drogerie_kosmetik_3', 'drogerie_kosmetik', '2900000000135',
         {'obf': off(name_de='Handcreme Sanftzeit 75 ml', brands='Sanftzeit', quantity='75 ml', categories='de:koerperpflege,en:other')},
         'Handcreme', 'Sanftzeit', '75 ml', 'koerperpflege', None, ('P16', 'P19', 'P2', 'P3')),
    case('drogerie_kosmetik_4', 'drogerie_kosmetik', '2900000000136',
         {'obf': off(name_de='Wattepads 80 Stk', brands='Sanftzeit', categories='de:koerperpflege,en:other', image='https://images.example.org/corpus/136.jpg')},
         'Wattepads', 'Sanftzeit', '80 Stk', 'koerperpflege', 'https://images.example.org/corpus/136.jpg', ('P15', 'P16', 'P19', 'P4')),
    case('drogerie_kosmetik_5', 'drogerie_kosmetik', '2900000000137',
         {'obf': off(name_de='Bodylotion', brands='Sanftzeit', quantity='250 ml', pq=250.0, pq_unit='ml', categories='de:koerperpflege,en:other')},
         'Bodylotion', 'Sanftzeit', '250 ml', 'koerperpflege', None, ('P16', 'P19', 'P5')),
    case('drogerie_kosmetik_6', 'drogerie_kosmetik', '2900000000138',
         {'obf': off(name_de='ZAHNPASTA', brands='Sanftzeit', quantity='75 ml', categories='de:koerperpflege,en:other')},
         'Zahnpasta', 'Sanftzeit', '75 ml', 'koerperpflege', None, ('P16', 'P19', 'P5', 'P6')),
    case('drogerie_kosmetik_7', 'drogerie_kosmetik', '2900000000139',
         {'obf': off(name_de='gesichtscreme', brands='Sanftzeit', quantity='50 ml', categories='de:koerperpflege,en:other', image='https://images.example.org/corpus/139.jpg')},
         'Gesichtscreme', 'Sanftzeit', '50 ml', 'koerperpflege', 'https://images.example.org/corpus/139.jpg', ('P16', 'P19', 'P5', 'P6')),
    case('drogerie_kosmetik_8', 'drogerie_kosmetik', '2900000000140',
         {'obf': off(name_de='Fu\xc3\x9fcreme', brands='Sanftzeit', quantity='100 ml', categories='de:koerperpflege,en:other')},
         'Fu\xdfcreme', 'Sanftzeit', '100 ml', 'koerperpflege', None, ('P16', 'P19', 'P7')),
    case('drogerie_kosmetik_9', 'drogerie_kosmetik', '2900000000141',
         {'obf': off(name_de='Sanftzeit Sonnencreme Naturhof 2 x 250 ml', brands='Sanftzeit,Naturhof', quantity='2 x 250 ml', categories='de:koerperpflege,en:other')},
         'Sonnencreme', 'Sanftzeit', '2 x 250 ml', 'koerperpflege', None, ('P1', 'P15', 'P16', 'P19', 'P3', 'P8')),
    case('drogerie_kosmetik_10', 'drogerie_kosmetik', '2900000000142',
         {'obf': off(name_de='Seife', quantity='100 g', categories='de:koerperpflege,en:other', image='https://images.example.org/corpus/142.jpg')},
         'Seife', None, '100 g', 'koerperpflege', 'https://images.example.org/corpus/142.jpg', ('P10', 'P16', 'P19', 'P5')),
    case('drogerie_kosmetik_11', 'drogerie_kosmetik', '2900000000143',
         {'obf': off(name='Hair Conditioner', brands='Sanftzeit', quantity='250 ml', categories='de:koerperpflege,en:other')},
         'Hair Conditioner', 'Sanftzeit', '250 ml', 'koerperpflege', None, ('P11', 'P16', 'P19')),
    case('drogerie_kosmetik_12', 'drogerie_kosmetik', '2900000000144',
         {'off': off(name_de='Deodorant', brands='Sanftzeit', quantity='150 ml', categories='de:koerperpflege'), 'obf': off(name_de='Deodorant', brands='Sanftzeit', quantity='150 ml', categories='de:koerperpflege'), 'opf': off(name_de='Deodorant 150 ml', brands='Sanftzeit', categories='de:koerperpflege')},
         'Deodorant', 'Sanftzeit', '150 ml', 'koerperpflege', None, ('P11', 'P12', 'P16', 'P19')),
    case('tiernahrung_1', 'tiernahrung', '2900000000145',
         {'opff': off(name_de='Pfotenliebe Katzenfutter Huhn 400g', brands='Pfotenliebe', quantity='400 g', categories='de:tiernahrung,en:other', image='https://images.example.org/corpus/145.jpg')},
         'Katzenfutter Huhn', 'Pfotenliebe', '400 g', 'tiernahrung', 'https://images.example.org/corpus/145.jpg', ('P1', 'P15', 'P16', 'P19', 'P3')),
    case('tiernahrung_2', 'tiernahrung', '2900000000146',
         {'opff': off(name_de='Hundefutter Rind Pfotenliebe 750 g', brands='Pfotenliebe', quantity='750 g', categories='de:tiernahrung,en:other')},
         'Hundefutter Rind', 'Pfotenliebe', '750 g', 'tiernahrung', None, ('P15', 'P16', 'P19', 'P2', 'P3')),
    case('tiernahrung_3', 'tiernahrung', '2900000000147',
         {'opff': off(name_de='Kaninchenfutter Pfotenliebe 500 g', brands='Pfotenliebe', quantity='500 g', categories='de:tiernahrung,en:other')},
         'Kaninchenfutter', 'Pfotenliebe', '500 g', 'tiernahrung', None, ('P16', 'P19', 'P2', 'P3')),
    case('tiernahrung_4', 'tiernahrung', '2900000000148',
         {'opff': off(name_de='Katzenfutter Lachs 2 x 250 g', brands='Pfotenliebe', categories='de:tiernahrung,en:other', image='https://images.example.org/corpus/148.jpg')},
         'Katzenfutter Lachs', 'Pfotenliebe', '2 x 250 g', 'tiernahrung', 'https://images.example.org/corpus/148.jpg', ('P15', 'P16', 'P19', 'P4')),
    case('tiernahrung_5', 'tiernahrung', '2900000000149',
         {'opff': off(name_de='Hundekekse', brands='Pfotenliebe', quantity='1 kg', pq=1.0, pq_unit='kg', categories='de:tiernahrung,en:other')},
         'Hundekekse', 'Pfotenliebe', '1 kg', 'tiernahrung', None, ('P16', 'P19', 'P5')),
    case('tiernahrung_6', 'tiernahrung', '2900000000150',
         {'opff': off(name_de='VOGELFUTTER', brands='Pfotenliebe', quantity='1 kg', categories='de:tiernahrung,en:other')},
         'Vogelfutter', 'Pfotenliebe', '1 kg', 'tiernahrung', None, ('P16', 'P19', 'P5', 'P6')),
    case('tiernahrung_7', 'tiernahrung', '2900000000151',
         {'opff': off(name_de='katzenstreu', brands='Pfotenliebe', quantity='500 g', categories='de:tiernahrung,en:other', image='https://images.example.org/corpus/151.jpg')},
         'Katzenstreu', 'Pfotenliebe', '500 g', 'tiernahrung', 'https://images.example.org/corpus/151.jpg', ('P16', 'P19', 'P5', 'P6')),
    case('tiernahrung_8', 'tiernahrung', '2900000000152',
         {'opff': off(name_de='H\xc3\xa4hnerleckerli', brands='Pfotenliebe', quantity='250 g', categories='de:tiernahrung,en:other')},
         'H\xe4hnerleckerli', 'Pfotenliebe', '250 g', 'tiernahrung', None, ('P16', 'P19', 'P7')),
    case('tiernahrung_9', 'tiernahrung', '2900000000153',
         {'opff': off(name_de='Pfotenliebe Fischfutter Naturhof 2x250g', brands='Pfotenliebe,Naturhof', quantity='2 x 250 g', categories='de:tiernahrung,en:other')},
         'Fischfutter', 'Pfotenliebe', '2 x 250 g', 'tiernahrung', None, ('P1', 'P15', 'P16', 'P19', 'P3', 'P8')),
    case('tiernahrung_10', 'tiernahrung', '2900000000154',
         {'opff': off(name_de='Heu', quantity='10 Stk', categories='de:tiernahrung,en:other', image='https://images.example.org/corpus/154.jpg')},
         'Heu', None, '10 Stk', 'tiernahrung', 'https://images.example.org/corpus/154.jpg', ('P10', 'P16', 'P19', 'P5')),
    case('tiernahrung_11', 'tiernahrung', '2900000000155',
         {'opff': off(name='Dog Food Turkey', brands='Pfotenliebe', quantity='500 g', categories='de:tiernahrung,en:other')},
         'Dog Food Turkey', 'Pfotenliebe', '500 g', 'tiernahrung', None, ('P11', 'P15', 'P16', 'P19')),
    case('tiernahrung_12', 'tiernahrung', '2900000000156',
         {'off': off(name_de='Katzenfutter Ente', brands='Pfotenliebe', quantity='400 g', categories='de:tiernahrung'), 'obf': off(name_de='Katzenfutter Ente', brands='Pfotenliebe', quantity='400 g', categories='de:tiernahrung'), 'opf': off(name_de='Katzenfutter Ente 400 g', brands='Pfotenliebe', categories='de:tiernahrung')},
         'Katzenfutter Ente', 'Pfotenliebe', '400 g', 'tiernahrung', None, ('P11', 'P12', 'P15', 'P16', 'P19')),
    case('baby_bio_sonstiges_1', 'baby_bio_sonstiges', '2900000000157',
         {'off': off(name_de='Bio Milch 1 l', brands='Bio', quantity='1 l', categories='de:baby-bio,en:other', image='https://images.example.org/corpus/157.jpg')},
         'Milch', 'Bio', '1 l', 'baby bio', 'https://images.example.org/corpus/157.jpg', ('P1', 'P14', 'P16', 'P19', 'P3')),
    case('baby_bio_sonstiges_2', 'baby_bio_sonstiges', '2900000000158',
         {'off': off(name_de='Babybrei Apfel REWE Bio 750 g', brands='REWE Bio', quantity='750 g', categories='de:baby-bio,en:other')},
         'Babybrei Apfel', 'REWE Bio', '750 g', 'baby bio', None, ('P14', 'P16', 'P19', 'P2', 'P3')),
    case('baby_bio_sonstiges_3', 'baby_bio_sonstiges', '2900000000159',
         {'off': off(name_de='Reiswaffeln REWE Bio 500 g', brands='REWE Bio', quantity='500 g', categories='de:baby-bio,en:other')},
         'Reiswaffeln', 'REWE Bio', '500 g', 'baby bio', None, ('P14', 'P16', 'P19', 'P2', 'P3')),
    case('baby_bio_sonstiges_4', 'baby_bio_sonstiges', '2900000000160',
         {'off': off(name_de='Windeln 2 x 250 g', brands='REWE Bio', categories='de:baby-bio,en:other', image='https://images.example.org/corpus/160.jpg')},
         'Windeln', 'REWE Bio', '2 x 250 g', 'baby bio', 'https://images.example.org/corpus/160.jpg', ('P14', 'P15', 'P16', 'P19', 'P4')),
    case('baby_bio_sonstiges_5', 'baby_bio_sonstiges', '2900000000161',
         {'off': off(name_de='Haferbrei', brands='REWE Bio', quantity='1 kg', pq=1.0, pq_unit='kg', categories='de:baby-bio,en:other')},
         'Haferbrei', 'REWE Bio', '1 kg', 'baby bio', None, ('P14', 'P16', 'P19', 'P5')),
    case('baby_bio_sonstiges_6', 'baby_bio_sonstiges', '2900000000162',
         {'off': off(name_de='DINKELKEKSE', brands='REWE Bio', quantity='1 kg', categories='de:baby-bio,en:other')},
         'Dinkelkekse', 'REWE Bio', '1 kg', 'baby bio', None, ('P14', 'P16', 'P19', 'P5', 'P6')),
    case('baby_bio_sonstiges_7', 'baby_bio_sonstiges', '2900000000163',
         {'off': off(name_de='karottenbrei', brands='REWE Bio', quantity='500 g', categories='de:baby-bio,en:other', image='https://images.example.org/corpus/163.jpg')},
         'Karottenbrei', 'REWE Bio', '500 g', 'baby bio', 'https://images.example.org/corpus/163.jpg', ('P14', 'P16', 'P19', 'P5', 'P6')),
    case('baby_bio_sonstiges_8', 'baby_bio_sonstiges', '2900000000164',
         {'off': off(name_de='Gem\xc3\xbcsebrei', brands='REWE Bio', quantity='250 g', categories='de:baby-bio,en:other')},
         'Gem\xfcsebrei', 'REWE Bio', '250 g', 'baby bio', None, ('P14', 'P16', 'P19', 'P7')),
    case('baby_bio_sonstiges_9', 'baby_bio_sonstiges', '2900000000165',
         {'off': off(name_de='REWE Bio Bio Milch 2 x 250 ml', brands='REWE Bio,Naturhof', quantity='2 x 250 ml', categories='de:baby-bio,en:other')},
         'Bio Milch', 'REWE Bio', '2 x 250 ml', 'baby bio', None, ('P1', 'P14', 'P15', 'P16', 'P19', 'P3', 'P8')),
    case('baby_bio_sonstiges_10', 'baby_bio_sonstiges', '2900000000166',
         {'off': off(name_de='Babytee', quantity='10 Stk', categories='de:baby-bio,en:other', image='https://images.example.org/corpus/166.jpg')},
         'Babytee', None, '10 Stk', 'baby bio', 'https://images.example.org/corpus/166.jpg', ('P10', 'P14', 'P16', 'P19', 'P5')),
    case('baby_bio_sonstiges_11', 'baby_bio_sonstiges', '2900000000167',
         {'off': off(name='Apple Puree', brands='REWE Bio', quantity='500 g', categories='de:baby-bio,en:other')},
         'Apple Puree', 'REWE Bio', '500 g', 'baby bio', None, ('P11', 'P14', 'P16', 'P19')),
    case('baby_bio_sonstiges_12', 'baby_bio_sonstiges', '2900000000168',
         {'off': off(name_de='Linsen', brands='REWE Bio', quantity='400 g', categories='de:baby-bio'), 'obf': off(name_de='Linsen', brands='REWE Bio', quantity='400 g', categories='de:baby-bio'), 'opf': off(name_de='Linsen 400 g', brands='REWE Bio', categories='de:baby-bio')},
         'Linsen', 'REWE Bio', '400 g', 'baby bio', None, ('P11', 'P12', 'P14', 'P16', 'P19')),
    case('edge_1', 'edge_cases', '2900000000169',
         {'off': off(name_de='Frisch vom Metzger')},
         None, None, None, None, None, ('P10', 'P19', 'P9')),
    case('edge_2', 'edge_cases', '2900000000170',
         {'off': off(name_de='Lecker Pizza')},
         None, None, None, None, None, ('P10', 'P19', 'P9')),
    case('edge_3', 'edge_cases', '2900000000171',
         {'off': off(name_de='Aus der Region')},
         None, None, None, None, None, ('P10', 'P19', 'P9')),
    case('edge_4', 'edge_cases', '2900000000172',
         {'off': off(name_de='Neu:')},
         None, None, None, None, None, ('P10', 'P19', 'P9')),
    case('edge_5', 'edge_cases', '2900000000173',
         {'off': off(name_de='Unser Bestes')},
         None, None, None, None, None, ('P10', 'P19', 'P9')),
    case('edge_6', 'edge_cases', '2900000000174',
         {'off': off(name_de='Frisch vom Bauern')},
         None, None, None, None, None, ('P10', 'P19', 'P9')),
    case('edge_7', 'edge_cases', '2900000000175',
         {'off': {'status': 0}, 'obf': {'status': 0}, 'opff': {'status': 0}, 'opf': {'status': 0}},
         None, None, None, None, None, ('P13', 'P19')),
    case('edge_8', 'edge_cases', '2900000000176',
         {'off': {'status': 0}, 'obf': {'status': 0}, 'opff': {'status': 0}, 'opf': {'status': 0}},
         None, None, None, None, None, ('P13', 'P19')),
    case('edge_9', 'edge_cases', '2900000000177',
         {'off': {'status': 0}, 'obf': {'status': 0}, 'opff': {'status': 0}, 'opf': {'status': 0}},
         None, None, None, None, None, ('P13', 'P19')),
    case('edge_10', 'edge_cases', '2900000000178',
         {'off': {'status': 0}, 'obf': {'status': 0}, 'opff': {'status': 0}, 'opf': {'status': 0}},
         None, None, None, None, None, ('P13', 'P19')),
    case('edge_11', 'edge_cases', '2900000000179',
         {'off': {'status': 0}, 'obf': {'status': 0}, 'opff': {'status': 0}, 'opf': {'status': 0}},
         None, None, None, None, None, ('P13', 'P19')),
    case('edge_12', 'edge_cases', '2900000000180',
         {'off': {'status': 0}, 'obf': {'status': 0}, 'opff': {'status': 0}, 'opf': {'status': 0}},
         None, None, None, None, None, ('P13', 'P19')),
    case('edge_13', 'edge_cases', '2900000000181',
         {'opf': off(name_de='2,99 EUR', image='not a URL')},
         None, None, None, None, None, ('P17', 'P19')),
    case('edge_14', 'edge_cases', '2900000000182',
         {'opf': off(name_de='@@@ ||| 9QZ', image='not a URL')},
         None, None, None, None, None, ('P17', 'P19')),
    case('edge_15', 'edge_cases', '2900000000183',
         {'opf': off(name_de='\u20ac 1,49 / AKTION', image='not a URL')},
         None, None, None, None, None, ('P17', 'P19')),
    case('edge_16', 'edge_cases', '2900000000184',
         {'opf': off(name_de='### 2,99 EUR ###', image='not a URL')},
         None, None, None, None, None, ('P17', 'P19')),
    case('edge_17', 'edge_cases', '2900000000185',
         {'opf': off(name_de='0O0 ||| ???', image='not a URL')},
         None, None, None, None, None, ('P17', 'P19')),
    case('edge_18', 'edge_cases', '2900000000186',
         {'opf': off(name_de='EUR 9,99 123456', image='not a URL')},
         None, None, None, None, None, ('P17', 'P19')),
    case('edge_19', 'edge_cases', '2900000000187',
         {'off': off(name_de='Milka 100g', brands='Milka', quantity='100 g')},
         None, 'Milka', '100 g', None, None, ('P1', 'P18', 'P19', 'P3')),
    case('edge_20', 'edge_cases', '2900000000188',
         {'off': off(name_de='Bio 100g', brands='Bio', quantity='100 g')},
         None, 'Bio', '100 g', None, None, ('P1', 'P18', 'P19', 'P3')),
    case('edge_21', 'edge_cases', '2900000000189',
         {'off': off(name_de='Alpenhof 100g', brands='Alpenhof', quantity='100 g')},
         None, 'Alpenhof', '100 g', None, None, ('P1', 'P18', 'P19', 'P3')),
    case('edge_22', 'edge_cases', '2900000000190',
         {'off': off(name_de='Kornland 100g', brands='Kornland', quantity='100 g')},
         None, 'Kornland', '100 g', None, None, ('P1', 'P18', 'P19', 'P3')),
    case('edge_23', 'edge_cases', '2900000000191',
         {'off': off(name_de='Quellklar 100g', brands='Quellklar', quantity='100 g')},
         None, 'Quellklar', '100 g', None, None, ('P1', 'P18', 'P19', 'P3')),
    case('edge_24', 'edge_cases', '2900000000192',
         {'off': off(name_de='Naschwerk 100g', brands='Naschwerk', quantity='100 g')},
         None, 'Naschwerk', '100 g', None, None, ('P1', 'P18', 'P19', 'P3')),
]

CORPUS.extend([
    case("naming_polish_0", "edge_cases", "2900000009000",
         {"off": off(name_de='Rittersport Alpenmilch 100 g', brands='Ritter Sport', quantity="100 g")},
         'Alpenmilch', 'Ritter Sport', "100 g", None),
    case("naming_polish_1", "edge_cases", "2900000009001",
         {"off": off(name_de='Coca Cola 100 g', brands='Coca-Cola', quantity="100 g")},
         None, 'Coca-Cola', "100 g", None),
    case("naming_polish_2", "edge_cases", "2900000009002",
         {"off": off(name_de='CocaCola 100 g', brands='Coca-Cola', quantity="100 g")},
         None, 'Coca-Cola', "100 g", None),
    case("naming_polish_3", "edge_cases", "2900000009003",
         {"off": off(name_de='Dr Oetker Pizza 100 g', brands='Dr. Oetker', quantity="100 g")},
         'Pizza', 'Dr. Oetker', "100 g", None),
    case("naming_polish_4", "edge_cases", "2900000009004",
         {"off": off(name_de='Gut&Günstig Spaghetti 100 g', brands='Gut&Günstig', quantity="100 g")},
         'Spaghetti', 'Gut&Günstig', "100 g", None),
    case("naming_polish_5", "edge_cases", "2900000009005",
         {"off": off(name_de='Pringles Original 100 g', brands='Pringles', quantity="100 g")},
         None, 'Pringles', "100 g", None),
    case("naming_polish_6", "edge_cases", "2900000009006",
         {"off": off(name_de='Test Zero Light 100 g', brands='Test', quantity="100 g")},
         None, 'Test', "100 g", None),
    case("naming_polish_7", "edge_cases", "2900000009007",
         {"off": off(name_de='Test Bio 100 g', brands='Test', quantity="100 g")},
         None, 'Test', "100 g", None),
])
