"""initial schema

Revision ID: cfe82b2fc527
Revises: 
Create Date: 2026-09-04 22:13:01.958921

"""
from alembic import op
import sqlalchemy as sa


revision = 'cfe82b2fc527'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('change_kind', sa.String(length=16), nullable=False),
    sa.Column('snapshot', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_log_revision'), 'change_log', ['revision'], unique=False)
    op.create_table('devices',
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('device_id'),
    sa.UniqueConstraint('token_hash', name='uq_device_token_hash')
    )
    op.create_table('locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name', name='uq_location_normalized_name')
    )
    op.create_table('mhd_warning_ack_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acknowledged_signature', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pairing_codes',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('processed_operations',
    sa.Column('operation_id', sa.String(length=36), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('result_snapshot', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('operation_id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('min_stock', sa.Integer(), nullable=True),
    sa.Column('content_unit_label', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revision_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_revision', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(
        "INSERT INTO revision_counter (id, current_revision) VALUES (0, 0)"
    )
    op.create_table('stores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name', name='uq_store_normalized_name')
    )
    op.create_table('barcodes',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('consumption_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('stock_kind', sa.String(length=16), nullable=False),
    sa.Column('content_unit_label', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('source_device_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('correction_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('stock_kind', sa.String(length=16), nullable=False),
    sa.Column('content_unit_label', sa.String(length=64), nullable=True),
    sa.Column('old_quantity', sa.Integer(), nullable=False),
    sa.Column('new_quantity', sa.Integer(), nullable=False),
    sa.Column('mhd_for_increase', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('source_device_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=True),
    sa.Column('price_per_unit_cents', sa.Integer(), nullable=True),
    sa.Column('mhd', sa.String(length=10), nullable=True),
    sa.Column('content_unit_label', sa.String(length=64), nullable=True),
    sa.Column('content_total', sa.Integer(), nullable=True),
    sa.Column('content_breakdown', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('source_device_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relocation_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('from_location_id', sa.String(length=36), nullable=False),
    sa.Column('to_location_id', sa.String(length=36), nullable=False),
    sa.Column('stock_kind', sa.String(length=16), nullable=False),
    sa.Column('content_unit_label', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('source_device_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('purchase_event_id', sa.String(length=36), nullable=True),
    sa.Column('correction_event_id', sa.String(length=36), nullable=True),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('mhd', sa.String(length=10), nullable=True),
    sa.Column('event_timestamp', sa.Integer(), nullable=False),
    sa.Column('is_content_tracked', sa.Boolean(), nullable=False),
    sa.Column('content_unit_label', sa.String(length=64), nullable=True),
    sa.Column('remaining_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['correction_event_id'], ['correction_events.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_event_id'], ['purchase_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM revision_counter WHERE id = 0")
    op.drop_table('batches')
    op.drop_table('relocation_events')
    op.drop_table('purchase_events')
    op.drop_table('correction_events')
    op.drop_table('consumption_events')
    op.drop_table('barcodes')
    op.drop_table('stores')
    op.drop_table('revision_counter')
    op.drop_table('products')
    op.drop_table('processed_operations')
    op.drop_table('pairing_codes')
    op.drop_table('mhd_warning_ack_state')
    op.drop_table('locations')
    op.drop_table('devices')
    op.drop_index(op.f('ix_change_log_revision'), table_name='change_log')
    op.drop_table('change_log')
    # ### end Alembic commands ###
